import { useState } from "react";
import type { ShootDay, Shot, StoryboardProject, StoryboardScene } from "../domain/storyboard";

type Props = { project: StoryboardProject; onUpdateScene: (scene: StoryboardScene) => void | Promise<void>; onCreateShootDay?: (input: Pick<ShootDay, "title" | "shootDate">) => void | Promise<void>; onUpdateShootDay?: (shootDay: ShootDay) => void | Promise<void>; onDeleteShootDay?: (id: string) => void | Promise<void>; onAssignShots?: (ids: string[], shootDayId: string | null) => void | Promise<void>; onReorderShots?: (shootDayId: string, ids: string[]) => void | Promise<void> };
const duration = (shot: Shot) => Number(shot.values.durationSeconds) || 0;
function Card({ shot, children }: { shot: Shot; children?: React.ReactNode }) { return <article className="shoot-plan__card"><div><strong>镜头 {shot.values.shotNumber || "—"}</strong><p>{shot.values.content || "未填写内容"}</p><span>{shot.values.shotSize || "景别待定"} · {duration(shot) || "未填"} 秒 · {shot.values.productionStatus || "待制作"}</span></div>{children}</article>; }

export function ShootPlan({ project, onUpdateScene: _onUpdateScene, onCreateShootDay, onUpdateShootDay, onDeleteShootDay, onAssignShots, onReorderShots }: Props) {
  const days = project.shootDays ?? [];
  const [dayId, setDayId] = useState(days[0]?.id ?? ""); const [title, setTitle] = useState(""); const [shootDate, setShootDate] = useState(""); const [picked, setPicked] = useState<string[]>([]);
  const day = days.find((item) => item.id === dayId);
  const queued = project.shots.filter((shot) => !shot.shootDayId);
  const scheduled = project.shots.filter((shot) => shot.shootDayId === dayId).sort((a, b) => (a.shootOrder ?? 0) - (b.shootOrder ?? 0));
  const total = project.shots.reduce((sum, shot) => sum + duration(shot), 0); const confirmed = project.shots.filter((shot) => shot.values.productionStatus === "已确认").length;
  const shift = (id: string, direction: -1 | 1) => { const index = scheduled.findIndex((shot) => shot.id === id); const to = index + direction; if (!day || !onReorderShots || to < 0 || to >= scheduled.length) return; const next = [...scheduled]; [next[index], next[to]] = [next[to], next[index]]; void onReorderShots(day.id, next.map((shot) => shot.id)); };
  return <section aria-label="拍摄计划" className="shoot-plan"><header><p>PRODUCTION SCHEDULE</p><h2>拍摄日工作台</h2><span>按镜头排程，场次归属与故事板顺序保持不变。</span></header><div className="shoot-plan__workbench">
    <aside className="shoot-plan__pool"><h3>待排镜头 <span>{queued.length}</span></h3>{queued.map((shot) => <Card key={shot.id} shot={shot}><label><input aria-label={`选择镜头 ${shot.values.shotNumber || shot.id}`} type="checkbox" checked={picked.includes(shot.id)} onChange={() => setPicked((current) => current.includes(shot.id) ? current.filter((id) => id !== shot.id) : [...current, shot.id])} /></label></Card>)}</aside>
    <section className="shoot-plan__timeline"><h3>拍摄日</h3><label>名称<input aria-label="拍摄日名称" value={title} onChange={(event) => setTitle(event.currentTarget.value)} /></label><label>日期<input aria-label="拍摄日日期" type="date" value={shootDate} onChange={(event) => setShootDate(event.currentTarget.value)} /></label><button type="button" onClick={() => { void onCreateShootDay?.({ title, shootDate }); setTitle(""); setShootDate(""); }}>新建拍摄日</button><select aria-label="选择拍摄日" value={dayId} onChange={(event) => setDayId(event.currentTarget.value)}><option value="">选择拍摄日</option>{days.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select>{day ? <><h4>{day.title} · {day.shootDate || "日期待定"}</h4><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void onUpdateShootDay?.({ ...day, location: String(form.get("location")), callTime: String(form.get("callTime")), wrapTime: String(form.get("wrapTime")), coordinator: String(form.get("coordinator")), notes: String(form.get("notes")) }); }}><label>拍摄地点<input aria-label="拍摄地点" name="location" defaultValue={day.location} /></label><label>集合时间<input aria-label="集合时间" name="callTime" defaultValue={day.callTime} /></label><label>收工时间<input aria-label="收工时间" name="wrapTime" defaultValue={day.wrapTime} /></label><label>负责人<input aria-label="负责人" name="coordinator" defaultValue={day.coordinator} /></label><label>制作备注<input aria-label="制作备注" name="notes" defaultValue={day.notes} /></label><button type="submit">保存制作资料</button></form><button type="button" disabled={!picked.length} onClick={() => { void onAssignShots?.(picked, day.id); setPicked([]); }}>加入所选镜头</button>{scheduled.length ? scheduled.map((shot) => <Card key={shot.id} shot={shot}><button type="button" onClick={() => shift(shot.id, -1)}>↑</button><button type="button" onClick={() => shift(shot.id, 1)}>↓</button><button type="button" onClick={() => void onAssignShots?.([shot.id], null)}>移出</button></Card>) : <p className="shoot-plan__empty">从左侧选择镜头并加入当前拍摄日。</p>}</> : <p className="shoot-plan__empty">先创建或选择一个拍摄日。</p>}</section>
    <aside className="shoot-plan__summary"><h3>当日摘要</h3><strong>{day?.title || "未选择拍摄日"}</strong><p>{day?.shootDate || "日期待定"} · {day?.location || "地点待定"}</p><p>{project.shots.length} 个镜头 · {total} 秒</p><p>{confirmed}/{project.shots.length} 已确认</p><p>集合 / 收工：{day?.callTime || "待定"} / {day?.wrapTime || "待定"}</p><p>负责人：{day?.coordinator || "待确认"}</p></aside>
    {day ? <button type="button" onClick={() => { if (window.confirm(`删除“${day.title}”？镜头将退回待排池。`)) void onDeleteShootDay?.(day.id); }}>删除拍摄日</button> : null}
  </div></section>;
}
